version: "3.9"
# Você terá 1.5 CPUs e 3.0GB 
services:
 db:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER:  rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '0.7GB'
 
 api1: &api
    image: rinha-backend-servlet 
    container_name: api1
    hostname:  api1
    depends_on:
        - dp
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '1.0GB'

 api2: 
    <<: *api
    container_name: api2


 nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
        - api1
        - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.2GB'
