version: "3.9"
# Você terá 1.5 CPUs e 3.0GB 
services:
 db:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER:  rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    command: 'postgres -c max_connections=210 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'  
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '0.9GB'
          
