version: "3.9"
# Você terá 1.5 CPUs e 3.0GB 
services:
 db:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER:  rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    command: 'postgres -c max_connections=210 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'  
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '0.9GB'
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready --dbname=rinha --username=rinha"]
#      interval: 20s
#      timeout: 5s
#      retries: 10
#      start_period: 10s    

 api1: &api
    build:
      context: .
    #image: davidlins/rinha-backend-servlet
    container_name: api1
    hostname:  api1
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    depends_on:
     db:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.9GB'

 api2: 
    <<: *api
    container_name: api2
    hostname:  api2


 nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
        - api1
        - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
