version: "3.9"
# Você terá 1.5 CPUs e 3.0GB 
services:
 db:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER:  rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    volumes:
      - ../db/init_db_trgm.sql:/docker-entrypoint-initdb.d/init_db.sql
    #  - ../db/postgresql.conf:/etc/postgresql/postgresql.conf 
    #command: postgres -c config_file=/etc/postgresql/postgresql.conf
    command: 'postgres -c max_connections=110 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c log_min_messages=panic -c log_min_error_statement=panic '  
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.1GB'
 
 api1:
    build:
      context: .
    container_name: api1
    hostname:  api1
    depends_on:
        - db
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.8GB'
    environment:
      postgres.host: postgres 
      postgres.connection.size: 45      

 api2:
    build:
      context: .
    container_name: api2
    hostname:  api2
    depends_on:
        - db
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.8GB'
    environment:
      postgres.host: postgres 
      postgres.connection.size: 45      

 nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
        - api1
        - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
         