version: "3.9"
# Você terá 1.5 CPUs e 3.0GB 
services:
 db:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER:  rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    volumes:
      - ../db/init_db_trgm.sql:/docker-entrypoint-initdb.d/init_db.sql
    command: 'postgres -c max_connections=110 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'  
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1.1GB'
    ports:
      - '5432:5432'
    network_mode: host      

 api1:
    build:
      context: .
    container_name: api1
    hostname:  api1
    depends_on:
        - db
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.8GB'
    environment:
      http.port:  8080
      postgres.host: localhost 
      postgres.connection.size: 45
    ports:
      - '8080:8080'
    network_mode: host        
    
 api2:
    build:
      context: .
    container_name: api2
    hostname:  api2
    depends_on:
        - db
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.8GB'
    environment:
      http.port:  8081
      postgres.host: localhost 
      postgres.connection.size: 45
    ports:
      - '8081:8081'
    network_mode: host
 
 nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ../nginx/nginx-host.conf:/etc/nginx/nginx.conf:ro
    depends_on:
        - api1
        - api2
    ports:
      - 9999:9999
    network_mode: host  
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
          